# Source: review/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-22T22:26:47Z"
  deletionTimestamp: null
  name: 'review-0.0.7'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.7
      sha: bfa311246b09fb2c93fe8fc0a4f141c8fe453bdf
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 4e8fcbed2bafec6859fe3aa3a9f9b46a47d2b12a
    - author:
        email: saschazauner@aol.com
        name: Sascha
      branch: master
      committer:
        email: saschazauner@aol.com
        name: Sascha
      message: |
        fix: sonarqube triggered in pull request now
      sha: 267e7c974c2f9544f5b36e59aa070477ec2bacbf
    - author:
        email: saschazauner@aol.com
        name: Sascha
      branch: master
      committer:
        email: saschazauner@aol.com
        name: Sascha
      message: |
        feat: added sonarqube task to pipeline
      sha: 34678a00dcdccb0868658954c25282267f21a677
  gitHttpUrl: https://github.com/BaPipe/review
  gitOwner: BaPipe
  gitRepository: review
  name: 'review'
  releaseNotesURL: https://github.com/BaPipe/review/releases/tag/v0.0.7
  version: v0.0.7
status: {}
