# Source: sonarqube/charts/postgresql/templates/secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: sonarqube-postgresql
  labels:
    app: postgresql
    chart: postgresql-8.2.0
    release: "sonarqube"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: gcpSecretsManager
  projectId: fair-expanse-297121
  data:
    - name: postgresql-password
      key: tf-jx-liberal-dove-sonarqube-postgresql
      property: postgresql-password
      version: latest
  template:
    metadata:
      labels:
        app: postgresql
        chart: postgresql-8.2.0
        release: "sonarqube"
        heritage: "Helm"
    type: Opaque
