# Source: sonarqube/templates/install-plugins.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-sonarqube-install-plugins
  labels:
    app: sonarqube
    chart: sonarqube-4.0.1
    release: sonarqube
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
data:
  install_plugins.sh: |-
    cd /opt/sonarqube/extensions/plugins/tmp
